### ISSUE TITLE
Датчики температуры и влажности

### ISSUE THREAD

**Issue by a-andreyev** [semiotproject/semiot-device-prototype#22]
## Требования к датчику
- 1 месяц от батарейки при опросе датчика раз в 30 минут
- кнопка конфигурирования
- корпус, в который ложатся все компоненты
  - в корпусе делаем отверстия для проникновения воздуха
  - отверстие под кнопку конфигурирования
## Требования к интерфейсу конфигурации
- логин и пароль Wi-Fi
- название
- адрес сервера
  - если пустое, то устройство должно пробовать найти Device Directory

Всего нужно собрать ~10 таких датчиков.

**Comment by nikitachrs** [comment]
Для сборки одного устройства предлагаю взять недостающие компоненты в магазине [tec](tec.org.ru) и [roboparts](roboparts.ru):
- расширительная плата   45 руб
- ams1117mini           85 руб
- батарейный отсек       25 руб
- кнопки                  10 руб
- корпус                  45/75 руб
- транзистор              3 руб
- мгтф                      4 руб
- dht22

По теоретическим расчётам, требуется корпус с размерами **90х56х30** или **112х79х32**. Стоимость закупки деталей для одного устройства составляет **240** руб. без включения стоимости самого модуля esp и dht.

**Comment by a-andreyev** [comment]
dht22 тоже придется взять, сейчас у нас только несколько 11-ых
